"use client";

import { useEffect, useMemo, useState } from "react";
import { Clock3, RefreshCw, Users } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";

type Appointment = { id: string; patient_name: string | null; clinician_name?: string | null; scheduled_for: string; status: string; encounter_id: string | null; reason: string | null };
type Encounter = { id: string; patient_name: string; encounter_type: string; status: string; diagnosis: string | null; created_at?: string };

export default function Page() {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [encounters, setEncounters] = useState<Encounter[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  async function load() { setBusy(true); setError(""); try { const [visits, activeEncounters] = await Promise.all([api.get<Appointment[]>("/api/v1/hospital/appointments"), api.get<Encounter[]>("/api/v1/hospital/encounters")]); setAppointments(visits); setEncounters(activeEncounters); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load patient queue."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  const waiting = useMemo(() => appointments.filter((item) => item.status === "checked_in"), [appointments]);
  const openEncounters = useMemo(() => encounters.filter((item) => item.status === "open"), [encounters]);
  return <DashboardShell title="Patient flow" subtitle="Check-in, waiting room, and active clinical encounters"><PermissionGate permission="hospital.appointments.read" module="hospital"><main className="mx-auto max-w-[1150px] space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Hospital operations</p><h1 className="mt-2 text-3xl font-bold">Patient flow queue</h1></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold"><RefreshCw size={16} /> Refresh</button></header>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<section className="grid gap-4 sm:grid-cols-3"><Metric label="Waiting for clinician" value={waiting.length} tone="amber" /><Metric label="Open encounters" value={openEncounters.length} tone="teal" /><Metric label="Total appointments" value={appointments.length} /></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Users className="text-teal-600" size={22} /><div><h2 className="text-xl font-bold">Waiting room</h2><p className="text-sm text-slate-500">Patients checked in and ready for clinical review.</p></div></div>{busy ? <p className="py-10 text-sm text-slate-500">Loading queue…</p> : !waiting.length ? <div className="py-12 text-center"><Clock3 className="mx-auto text-slate-300" size={36} /><p className="mt-3 font-bold text-slate-700">Waiting room is clear</p><p className="mt-1 text-sm text-slate-500">Checked-in appointments will appear here.</p></div> : <div className="mt-5 divide-y divide-slate-100">{waiting.map((item) => <article key={item.id} className="grid gap-3 py-4 sm:grid-cols-[150px_1fr_auto] sm:items-center"><p className="font-bold text-teal-700">{new Date(item.scheduled_for).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p><div><p className="font-bold">{item.patient_name || "Patient"}</p><p className="text-sm text-slate-500">{item.clinician_name || "Clinician to be assigned"}{item.reason ? ` · ${item.reason}` : ""}</p></div><span className="rounded-full bg-teal-50 px-3 py-1 text-center text-xs font-bold text-teal-700">Checked in</span></article>)}</div>}</section></main></PermissionGate></DashboardShell>;
}
function Metric({ label, value, tone = "slate" }: { label: string; value: number; tone?: "slate" | "amber" | "teal" }) { const colors = { slate: "text-slate-950", amber: "text-amber-600", teal: "text-teal-600" }; return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold text-slate-400">{label}</p><p className={`mt-2 text-2xl font-bold ${colors[tone]}`}>{value}</p></div>; }
