"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { API_BASE } from "@/lib/config";

export default function ResetPasswordPage() {
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const token = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("token") || "";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const password = String(form.get("password")); if (password !== String(form.get("confirm_password"))) { setError("Passwords do not match."); return; } try { const response = await fetch(`${API_BASE}/api/v1/auth/password/reset`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token: String(form.get("token")), new_password: password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Unable to reset password."); setMessage("Password reset. You can now sign in."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to reset password."); } }
  return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-600">Account recovery</p><h1 className="mt-2 text-3xl font-bold">Choose a new password</h1>{error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<label className="mt-5 block text-xs font-bold text-slate-600">Reset token<input name="token" defaultValue={token} required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><label className="mt-4 block text-xs font-bold text-slate-600">New password<input name="password" type="password" minLength={8} required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><label className="mt-4 block text-xs font-bold text-slate-600">Confirm password<input name="confirm_password" type="password" minLength={8} required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><button className="mt-5 w-full rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white">Reset password</button><Link href="/login" className="mt-5 block text-center text-sm font-bold text-teal-700">Back to sign in</Link></form></main>;
}
