"use client";

import { FormEvent, useEffect, useState } from "react";
import { FileImage, RefreshCw } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";

type Study = { id: string; patient_name: string; study_name: string; priority: string; status: string; report: string | null; scheduled_for?: string | null; modality?: string | null; room?: string | null; technician_id?: string | null; approved_at?: string | null; created_at?: string };
export default function Page() {
  const [items, setItems] = useState<Study[]>([]); const [selected, setSelected] = useState<Study | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setBusy(true); try { setItems(await api.get<Study[]>("/api/v1/hospital/radiology/orders")); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load radiology worklist."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; try { await api.post(`/api/v1/hospital/radiology/orders/${selected.id}/report`, { report: String(new FormData(event.currentTarget).get("report") || "") }); setSelected(null); setNotice("Radiology report saved."); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to save report."); } }
  return <DashboardShell title="Radiology worklist" subtitle="Imaging studies, reporting, and clinician hand-off"><PermissionGate permission="hospital.radiology.order" module="hospital"><main className="mx-auto max-w-[1100px] space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Diagnostics</p><h1 className="mt-2 text-3xl font-bold">Radiology worklist</h1></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold"><RefreshCw size={16} /> Refresh</button></header>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</p>}<section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{busy ? <p className="p-8 text-sm text-slate-500">Loading imaging studies…</p> : !items.length ? <p className="p-10 text-center text-sm text-slate-500">No radiology studies found.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><FileImage size={19} /></span><div className="min-w-0 flex-1"><p className="font-bold">{item.study_name}</p><p className="mt-1 text-sm text-slate-500">{item.patient_name} · {item.priority} priority</p>{item.report && <p className="mt-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{item.report}</p>}</div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize text-slate-600">{item.status}</span>{!item.report && <button onClick={() => setSelected(item)} className="rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-bold text-white">Enter report</button>}</article>)}</div>}</section>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => void submit(event)} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">Report: {selected.study_name}</h2><p className="mt-1 text-sm text-slate-500">{selected.patient_name}</p><textarea name="report" required rows={7} className="mt-5 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Findings and impression" /><div className="mt-5 flex gap-2"><button type="button" onClick={() => setSelected(null)} className="flex-1 rounded-xl border border-slate-200 py-3 text-sm font-bold">Cancel</button><button className="flex-1 rounded-xl bg-teal-600 py-3 text-sm font-bold text-white">Save report</button></div></form></div>}</main></PermissionGate></DashboardShell>;
}
