"use client";

import FormSelect from "@/components/form-select";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Banknote, CalendarDays, Landmark, Plus, ReceiptText, ShieldCheck, Users, WalletCards } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";
import type { AuthorizationContext } from "@/lib/authorization";
import { can } from "@/lib/authorization";

type Employee = { id: string; employee_number: string; name: string; department: string | null };
type Account = { id: string; code: string; name: string; account_type: string; active?: boolean };
type Policy = { id: string; name: string; effective_from: string; effective_to: string | null; active: boolean; currency: string; paye_brackets: Array<{ up_to: number | null; rate: number }>; pension_employee_rate: string; pension_employer_rate: string; nhf_rate: string; nsitf_employer_rate: string };
type Compensation = { id: string; employee_id: string; employee_name: string; effective_from: string; basic_salary: string; housing_allowance: string; transport_allowance: string; other_allowances: string; pension_enrolled: boolean; nhf_enrolled: boolean; nsitf_applicable: boolean };
type Loan = { id: string; employee_id: string; loan_number: string; purpose: string; principal: string; annual_interest_rate: string; first_repayment_on: string; term_months: number; installment_amount: string; outstanding_principal: string; status: string; installments: Array<{ id: string; due_on: string; total: string; paid: string; status: string }> };
type Run = { id: string; run_number: string; period_start: string; period_end: string; payment_date: string; status: string; gross_pay: string; net_pay: string; employer_cost: string; lines: Array<{ id: string; employee_id: string; gross_pay: string; pension_employee: string; pension_employer: string; nhf: string; nsitf_employer: string; paye: string; loan_principal: string; loan_interest: string; net_pay: string }>; remittances: Array<{ id: string; type: string; amount: string; due_on: string; status: string }> };
type Tab = "overview" | "compensation" | "loans" | "runs";

const legacyPayeBrackets = [
  { up_to: 300000, rate: 0.07 }, { up_to: 600000, rate: 0.11 }, { up_to: 1100000, rate: 0.15 },
  { up_to: 1600000, rate: 0.19 }, { up_to: 3200000, rate: 0.21 }, { up_to: null, rate: 0.24 },
];
const money = (value: string | number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN" }).format(Number(value || 0));
const fail = (error: unknown, fallback: string) => error instanceof ApiError ? error.message : fallback;

export default function PayrollPage() {
  const [tab, setTab] = useState<Tab>("overview"); const [employees, setEmployees] = useState<Employee[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [policies, setPolicies] = useState<Policy[]>([]); const [compensations, setCompensations] = useState<Compensation[]>([]); const [loans, setLoans] = useState<Loan[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [auth, setAuth] = useState<AuthorizationContext | null>(null);
  const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [issueLoan, setIssueLoan] = useState<Loan | null>(null); const [payRun, setPayRun] = useState<Run | null>(null); const [payRemittance, setPayRemittance] = useState<{ run: Run; id: string; type: string; amount: string } | null>(null);
  const assetAccounts = accounts.filter((account) => account.account_type === "asset" && account.active !== false);
  const load = useCallback(async () => {
    setBusy(true); const results = await Promise.allSettled([api.get<Employee[]>("/api/v1/payroll/employees"), api.get<Account[]>("/api/v1/accounting/accounts"), api.get<Policy[]>("/api/v1/payroll/policies"), api.get<Compensation[]>("/api/v1/payroll/compensations"), api.get<Loan[]>("/api/v1/payroll/loans"), api.get<Run[]>("/api/v1/payroll/runs"), api.get<AuthorizationContext>("/api/v1/auth/me/authorization")]);
    const setters = [setEmployees, setAccounts, setPolicies, setCompensations, setLoans, setRuns, setAuth]; results.forEach((result, index) => { if (result.status === "fulfilled") setters[index](result.value as never); }); const failed = results.find((result) => result.status === "rejected"); if (failed?.status === "rejected") setError(fail(failed.reason, "Unable to load payroll records.")); setBusy(false);
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(path: string, payload: unknown, success: string) { setSaving(true); setError(""); try { await api.post(path, payload); setNotice(success); await load(); } catch (caught) { setError(fail(caught, "Payroll action could not be completed.")); } finally { setSaving(false); } }
  function createPolicy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("/api/v1/payroll/policies", { name: String(form.get("name")), effective_from: String(form.get("effective_from")), paye_brackets: legacyPayeBrackets, consolidated_relief_fixed: "200000", consolidated_relief_rate: "0.20", consolidated_relief_minimum_rate: "0.01", minimum_tax_rate: "0.01", minimum_tax_threshold: "300000", pension_employee_rate: "0.08", pension_employer_rate: "0.10", nhf_rate: "0.025", nsitf_employer_rate: "0.01", remittance_days_paye: 10, remittance_days_pension: 7, remittance_days_nhf: 30 }, "Nigerian payroll policy saved. Confirm PAYE settings with your tax adviser before its first run."); }
  function createCompensation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("/api/v1/payroll/compensations", { employee_id: String(form.get("employee_id")), effective_from: String(form.get("effective_from")), basic_salary: String(form.get("basic_salary")), housing_allowance: String(form.get("housing_allowance") || "0"), transport_allowance: String(form.get("transport_allowance") || "0"), other_allowances: String(form.get("other_allowances") || "0"), pension_enrolled: form.get("pension_enrolled") === "on", nhf_enrolled: form.get("nhf_enrolled") === "on", nsitf_applicable: form.get("nsitf_applicable") === "on", pension_rsa_pin: String(form.get("pension_rsa_pin") || "") || null, pension_pfa: String(form.get("pension_pfa") || "") || null, nhf_number: String(form.get("nhf_number") || "") || null }, "Employee compensation saved."); }
  function createLoan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("/api/v1/payroll/loans", { employee_id: String(form.get("employee_id")), purpose: String(form.get("purpose")), principal: String(form.get("principal")), annual_interest_rate: String(form.get("annual_interest_rate") || "0"), first_repayment_on: String(form.get("first_repayment_on")), term_months: Number(form.get("term_months")) }, "Employee loan prepared. An independent approver must issue the disbursement."); }
  function createRun(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("/api/v1/payroll/runs", { period_start: String(form.get("period_start")), period_end: String(form.get("period_end")), payment_date: String(form.get("payment_date")) }, "Payroll run calculated and submitted for independent approval."); }
  return <DashboardShell title="Nigerian payroll" subtitle="NGN salaries, PAYE, pension, NHF, NSITF, employee loans, and auditable accounting"><PermissionGate permission="payroll.read"><div className="mx-auto max-w-[1400px] space-y-6">
    <header className="rounded-3xl border border-teal-100 bg-gradient-to-br from-teal-50 to-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-700">Statutory payroll control</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Nigeria payroll & employee loans</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-600">Payroll is a three-person control: preparer, independent approver, then poster. Salary payment and each PAYE, pension, NHF, and NSITF remittance produce their own balanced journal.</p></header>
    {error && <p className="rounded-2xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}{notice && <p className="rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</p>}
    <div className="grid gap-4 sm:grid-cols-4"><Metric icon={<Users size={18} />} label="Compensated staff" value={String(compensations.length)} /><Metric icon={<ReceiptText size={18} />} label="Open loans" value={String(loans.filter((loan) => loan.status === "active").length)} /><Metric icon={<WalletCards size={18} />} label="Latest net payroll" value={money(runs[0]?.net_pay || 0)} /><Metric icon={<CalendarDays size={18} />} label="Due remittances" value={String(runs.flatMap((run) => run.remittances).filter((item) => item.status === "due").length)} /></div>
    <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2">{(["overview", "compensation", "loans", "runs"] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-xl px-4 py-2 text-sm font-bold capitalize ${tab === item ? "bg-teal-50 text-teal-700" : "text-slate-500"}`}>{item === "compensation" ? "Staff salary" : item}</button>)}</div>
    {tab === "overview" && <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Panel title="Statutory policy" icon={<ShieldCheck size={19} />}><div className="space-y-3">{policies.map((policy) => <div key={policy.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{policy.name}</p><p className="mt-1 text-xs text-slate-500">Effective {policy.effective_from}{policy.effective_to ? ` to ${policy.effective_to}` : " onwards"} · {policy.currency}</p></div><span className="text-xs font-bold text-emerald-700">Active</span></div><p className="mt-3 text-xs text-slate-600">Pension: {Number(policy.pension_employee_rate) * 100}% employee + {Number(policy.pension_employer_rate) * 100}% employer · NHF: {Number(policy.nhf_rate) * 100}% basic · NSITF: {Number(policy.nsitf_employer_rate) * 100}% employer.</p></div>)}{!policies.length && <Empty text="Create the effective-dated statutory policy before preparing payroll." />}</div>{can(auth, "payroll.manage") && <form onSubmit={createPolicy} className="mt-5 grid gap-3 border-t border-slate-100 pt-5 sm:grid-cols-2"><Input name="name" label="Policy name" defaultValue="Nigeria PAYE / pension baseline" required /><Input name="effective_from" label="Effective from" type="date" required /><p className="sm:col-span-2 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900">The starting PAYE brackets use the legacy PITA schedule. Tax rules change; have a Nigerian tax professional confirm or replace the effective-dated schedule before posting a run.</p><button disabled={saving} className="sm:col-span-2 rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus className="mr-2 inline" size={16} />Save policy</button></form>}</Panel><Panel title="Control sequence" icon={<Landmark size={19} />}><ol className="space-y-3 text-sm text-slate-600"><li><strong>1. Configure salary:</strong> compensation records are effective-dated, so a raise never changes a prior payslip.</li><li><strong>2. Prepare run:</strong> payroll snapshots pay, statutory deductions, loan installments, and net salary.</li><li><strong>3. Approve then post:</strong> creator cannot approve; approver cannot post.</li><li><strong>4. Pay and remit:</strong> payment reduces salary payable; separate remittances reduce statutory liabilities.</li></ol></Panel></section>}
    {tab === "compensation" && <section className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Panel title="Set monthly compensation" icon={<Banknote size={19} />}><form onSubmit={createCompensation} className="grid gap-3 sm:grid-cols-2"><Select name="employee_id" label="Employee" required><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} · {employee.employee_number}</option>)}</Select><Input name="effective_from" label="Effective from" type="date" required /><Input name="basic_salary" label="Basic salary" type="number" required /><Input name="housing_allowance" label="Housing allowance" type="number" defaultValue="0" /><Input name="transport_allowance" label="Transport allowance" type="number" defaultValue="0" /><Input name="other_allowances" label="Other allowance" type="number" defaultValue="0" /><Input name="pension_pfa" label="PFA (optional)" /><Input name="pension_rsa_pin" label="RSA PIN (optional)" /><Input name="nhf_number" label="NHF number (optional)" /><Checks /><button disabled={saving} className="sm:col-span-2 rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Save salary configuration</button></form></Panel><Panel title="Compensation register" icon={<Users size={19} />}><div className="space-y-3">{compensations.map((item) => <div key={item.id} className="flex justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div><p className="font-bold">{item.employee_name}</p><p className="mt-1 text-xs text-slate-500">Effective {item.effective_from} · basic {money(item.basic_salary)} + allowances {money(Number(item.housing_allowance) + Number(item.transport_allowance) + Number(item.other_allowances))}</p></div><p className="text-xs font-bold text-teal-700">{item.pension_enrolled ? "Pension" : "No pension"} · {item.nhf_enrolled ? "NHF" : "No NHF"}</p></div>)}{!compensations.length && <Empty text="No employee compensation is configured." />}</div></Panel></section>}
    {tab === "loans" && <section className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Panel title="Employee loan" icon={<WalletCards size={19} />}><form onSubmit={createLoan} className="grid gap-3 sm:grid-cols-2"><Select name="employee_id" label="Employee" required><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} · {employee.employee_number}</option>)}</Select><Input name="purpose" label="Purpose" required /><Input name="principal" label="Principal (NGN)" type="number" required /><Input name="annual_interest_rate" label="Annual interest (0–1)" type="number" step="0.0001" defaultValue="0" /><Input name="first_repayment_on" label="First repayment" type="date" required /><Input name="term_months" label="Term (months)" type="number" defaultValue="12" required /><button disabled={saving} className="sm:col-span-2 rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Prepare loan schedule</button></form></Panel><Panel title="Loans and repayment schedule" icon={<ReceiptText size={19} />}><div className="space-y-3">{loans.map((loan) => <div key={loan.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{loan.loan_number} · {loan.purpose}</p><p className="mt-1 text-xs text-slate-500">{money(loan.principal)} · {loan.term_months} months · installment {money(loan.installment_amount)}</p></div><div className="text-right"><p className="text-xs font-bold capitalize text-teal-700">{loan.status.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-500">Outstanding {money(loan.outstanding_principal)}</p></div></div>{loan.status === "draft" && can(auth, "payroll.approve") && <button onClick={() => setIssueLoan(loan)} className="mt-3 rounded-xl border border-teal-200 bg-white px-3 py-2 text-xs font-bold text-teal-700">Issue after approval</button>}<p className="mt-3 text-xs text-slate-500">Next due: {loan.installments.find((item) => item.status === "due")?.due_on || "No outstanding installment"}</p></div>)}{!loans.length && <Empty text="No employee loans are recorded." />}</div></Panel></section>}
    {tab === "runs" && <section className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Panel title="Prepare payroll" icon={<CalendarDays size={19} />}><form onSubmit={createRun} className="grid gap-3"><Input name="period_start" label="Period start" type="date" required /><Input name="period_end" label="Period end" type="date" required /><Input name="payment_date" label="Planned payment date" type="date" required /><button disabled={saving || !policies.length || !compensations.length} className="rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Calculate payroll</button>{(!policies.length || !compensations.length) && <p className="text-xs text-amber-700">An active policy and at least one salary configuration are required.</p>}</form></Panel><Panel title="Payroll register" icon={<ReceiptText size={19} />}><div className="space-y-4">{runs.map((run) => <div key={run.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{run.run_number}</p><p className="mt-1 text-xs text-slate-500">{run.period_start} → {run.period_end} · {run.lines.length} staff</p></div><div className="text-right"><p className="text-xs font-bold capitalize text-teal-700">{run.status}</p><p className="mt-1 text-sm font-bold">Net {money(run.net_pay)}</p></div></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><span>Gross: <strong>{money(run.gross_pay)}</strong></span><span>Employer cost: <strong>{money(run.employer_cost)}</strong></span><span>PAYE: <strong>{money(run.lines.reduce((sum, line) => sum + Number(line.paye), 0))}</strong></span></div><div className="mt-4 flex flex-wrap gap-2">{run.status === "draft" && can(auth, "payroll.approve") && <Action onClick={() => void submit(`/api/v1/payroll/runs/${run.id}/approve`, {}, "Payroll independently approved.")}>Approve</Action>}{run.status === "approved" && can(auth, "payroll.post") && <Action onClick={() => void submit(`/api/v1/payroll/runs/${run.id}/post`, {}, "Payroll posted to the general ledger.")}>Post to GL</Action>}{run.status === "posted" && can(auth, "payroll.pay") && <Action onClick={() => setPayRun(run)}>Pay salaries</Action>}</div><div className="mt-4 space-y-2 border-t border-slate-100 pt-3">{run.remittances.map((item) => <div key={item.id} className="flex justify-between gap-3 text-xs"><span className="capitalize">{item.type} · due {item.due_on}</span><span><strong>{money(item.amount)}</strong> · {item.status}{item.status === "due" && can(auth, "payroll.remit") && <button onClick={() => setPayRemittance({ run, id: item.id, type: item.type, amount: item.amount })} className="ml-2 font-bold text-teal-700">Pay</button>}</span></div>)}</div></div>)}{!runs.length && <Empty text="No payroll run has been prepared." />}</div></Panel></section>}
    {busy && <p className="text-center text-sm text-slate-500">Refreshing payroll records…</p>}
  </div>{issueLoan && <PaymentDialog title={`Issue ${issueLoan.loan_number}`} accounts={assetAccounts} saving={saving} close={() => setIssueLoan(null)} submit={(form) => { void submit(`/api/v1/payroll/loans/${issueLoan.id}/issue`, { issued_on: String(form.get("paid_on")), disbursement_account_id: String(form.get("account_id")), reference: String(form.get("reference")) }, "Employee loan issued and posted."); setIssueLoan(null); }} />}{payRun && <PaymentDialog title={`Pay ${payRun.run_number}`} accounts={assetAccounts} saving={saving} close={() => setPayRun(null)} submit={(form) => { void submit(`/api/v1/payroll/runs/${payRun.id}/pay`, { paid_on: String(form.get("paid_on")), payment_account_id: String(form.get("account_id")), reference: String(form.get("reference")) }, "Payroll payment posted."); setPayRun(null); }} />}{payRemittance && <PaymentDialog title={`Pay ${payRemittance.type.toUpperCase()} · ${money(payRemittance.amount)}`} accounts={assetAccounts} saving={saving} close={() => setPayRemittance(null)} submit={(form) => { void submit(`/api/v1/payroll/remittances/${payRemittance.id}/pay`, { paid_on: String(form.get("paid_on")), payment_account_id: String(form.get("account_id")), reference: String(form.get("reference")) }, `${payRemittance.type.toUpperCase()} remittance posted.`); setPayRemittance(null); }} />}</PermissionGate></DashboardShell>;
}

function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-teal-600">{icon}<h2 className="text-xl font-bold text-slate-900">{title}</h2></div><div className="mt-5">{children}</div></section>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-teal-600">{icon}<p className="text-xs font-semibold text-slate-500">{label}</p></div><p className="mt-3 truncate text-2xl font-bold">{value}</p></section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">{text}</p>; }
function Input({ name, label, type = "text", defaultValue, required = false, step }: { name: string; label: string; type?: string; defaultValue?: string; required?: boolean; step?: string }) { return <label className="text-xs font-bold text-slate-600">{label}<input name={name} type={type} step={step} defaultValue={defaultValue} required={required} min={type === "number" ? "0" : undefined} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /></label>; }
function Select({ name, label, children, required = false }: { name: string; label: string; children: React.ReactNode; required?: boolean }) { return <label className="text-xs font-bold text-slate-600">{label}<FormSelect name={name} required={required} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm">{children}</FormSelect></label>; }
function Checks() { return <fieldset className="grid gap-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-600 sm:col-span-2"><label><input name="pension_enrolled" type="checkbox" defaultChecked className="mr-2" />Pension enrolled (8% employee / 10% employer baseline)</label><label><input name="nhf_enrolled" type="checkbox" defaultChecked className="mr-2" />NHF enrolled (2.5% of basic)</label><label><input name="nsitf_applicable" type="checkbox" defaultChecked className="mr-2" />NSITF applicable (1% employer payroll cost)</label></fieldset>; }
function Action({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} className="rounded-xl border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800">{children}</button>; }
function PaymentDialog({ title, accounts, saving, close, submit }: { title: string; accounts: Account[]; saving: boolean; close: () => void; submit: (form: FormData) => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); submit(new FormData(event.currentTarget)); }} className="w-full max-w-md rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-slate-500">Choose the asset account that actually pays the transaction. This creates a separate payment journal.</p><div className="mt-5 grid gap-4"><Select name="account_id" label="Payment account" required><option value="">Select cash or bank account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</Select><Input name="paid_on" label="Payment date" type="date" required /><Input name="reference" label="Bank / transfer reference" required /></div><div className="mt-6 flex gap-3"><button type="button" onClick={close} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</button><button disabled={saving || !accounts.length} className="flex-1 rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Post payment</button></div></form></div>; }
