"use client";

import FormSelect from "@/components/form-select";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Plus, ReceiptText, Search, ShieldCheck, X } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";

type Branch = { id: string; name: string; code: string };
type TaxRate = { id: string; name: string; rate: string };
type Expense = { id: string; branch_id: string | null; category: string; description: string; amount: string; tax_amount: string; payment_method: string; status: string; created_at: string };

export default function ExpensesPage() {
  const [branches, setBranches] = useState<Branch[]>([]); const [taxes, setTaxes] = useState<TaxRate[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]);
  const [branchId, setBranchId] = useState(""); const [query, setQuery] = useState(""); const [expenseOpen, setExpenseOpen] = useState(false); const [taxOpen, setTaxOpen] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(true);
  async function load() { setBusy(true); const results = await Promise.allSettled([api.get<Branch[]>("/api/v1/catalog/branches"), api.get<TaxRate[]>("/api/v1/store/taxes"), api.get<Expense[]>("/api/v1/store/expenses")]); if (results[0].status === "fulfilled") setBranches(results[0].value); if (results[1].status === "fulfilled") setTaxes(results[1].value); if (results[2].status === "fulfilled") setExpenses(results[2].value); const failed = results.find((result) => result.status === "rejected"); if (failed?.status === "rejected") setError(failed.reason instanceof ApiError ? failed.reason.message : "Unable to load expense records."); setBusy(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => expenses.filter((expense) => (!branchId || expense.branch_id === branchId) && `${expense.category} ${expense.description} ${expense.payment_method}`.toLowerCase().includes(query.toLowerCase())), [expenses, branchId, query]);
  const total = filtered.reduce((sum, item) => sum + Number(item.amount) + Number(item.tax_amount), 0); const taxTotal = filtered.reduce((sum, item) => sum + Number(item.tax_amount), 0);
  const branchName = (id: string | null) => branches.find((branch) => branch.id === id)?.name || "Company-wide";
  async function createExpense(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.post("/api/v1/store/expenses", { branch_id: String(form.get("branch_id") || "") || null, category: String(form.get("category")), description: String(form.get("description")), amount: String(form.get("amount")), tax_amount: String(form.get("tax_amount") || "0"), payment_method: String(form.get("payment_method")) }); setExpenseOpen(false); setNotice("Expense posted to the operating-expense ledger."); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to post expense."); } }
  async function createTax(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.post("/api/v1/store/taxes", { name: String(form.get("name")), rate: String(form.get("rate")) }); setTaxOpen(false); setNotice("Tax rate created."); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to create tax rate."); } }
  return <DashboardShell title="Expenses & taxes" subtitle="Post operating costs and maintain the tax rates used at checkout"><PermissionGate permission="expenses.read"><main className="mx-auto max-w-[1280px] space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Cost control</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Expenses & taxes</h1></div><div className="flex gap-2"><button onClick={() => setTaxOpen(true)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Manage tax rate</button><button onClick={() => setExpenseOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white"><Plus size={16} /> Post expense</button></div></div>
    {error && <Message color="rose" text={error} />}{notice && <Message color="emerald" text={notice} />}
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Posted expenses" value={String(filtered.length)} /><Metric label="Cost incl. tax" value={total.toFixed(2)} /><Metric label="Input tax" value={taxTotal.toFixed(2)} /></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_330px]"><section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search expense category, description, or payment method" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm" /></label><FormSelect value={branchId} onChange={(event) => setBranchId(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">All branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</FormSelect></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Expense</th><th className="px-3 py-3">Branch</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Tax</th><th className="px-5 py-3">Posted</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((expense) => <tr key={expense.id}><td className="px-5 py-4"><p className="font-semibold">{expense.category}</p><p className="mt-1 text-xs text-slate-500">{expense.description} · {expense.payment_method}</p></td><td className="px-3 py-4 text-slate-600">{branchName(expense.branch_id)}</td><td className="px-3 py-4 font-bold">{expense.amount}</td><td className="px-3 py-4">{expense.tax_amount}</td><td className="px-5 py-4 text-xs text-slate-500">{new Date(expense.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!filtered.length && <p className="p-10 text-center text-sm text-slate-500">{busy ? "Loading expense register…" : "No expenses found."}</p>}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="text-teal-600" size={20} /><div><h2 className="text-xl font-bold">Active tax rates</h2><p className="text-xs text-slate-400">Use these as the approved checkout tax reference.</p></div></div><div className="mt-5 space-y-3">{taxes.map((tax) => <div key={tax.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><p className="font-bold">{tax.name}</p><p className="text-lg font-bold text-teal-700">{tax.rate}%</p></div>)}{!taxes.length && <p className="text-sm text-slate-500">No active tax rates.</p>}</div></section></div>
    {expenseOpen && <Modal title="Post operating expense" close={() => setExpenseOpen(false)} submit={createExpense}><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Branch<FormSelect name="branch_id" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">Company-wide</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</FormSelect></label><Input name="category" label="Category" required /><Input name="description" label="Description" required wide /><Input name="amount" label="Expense amount" type="number" required /><Input name="tax_amount" label="Tax amount" type="number" /><label className="text-xs font-bold text-slate-600">Payment method<FormSelect name="payment_method" defaultValue="cash" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="mobile_money">Mobile money</option></FormSelect></label></div><p className="mt-4 rounded-xl bg-teal-50 p-3 text-xs text-teal-800">Posting records the expense, input tax, and payment in the general ledger.</p></Modal>}
    {taxOpen && <Modal title="Add tax rate" close={() => setTaxOpen(false)} submit={createTax}><div className="grid gap-4 sm:grid-cols-2"><Input name="name" label="Tax name" required /><Input name="rate" label="Rate (%)" type="number" required /></div></Modal>}
  </main></PermissionGate></DashboardShell>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
function Message({ color, text }: { color: "rose" | "emerald"; text: string }) { return <div className={`rounded-2xl border px-4 py-3 text-sm ${color === "rose" ? "border-rose-100 bg-rose-50 text-rose-700" : "border-emerald-100 bg-emerald-50 text-emerald-700"}`}>{text}</div>; }
function Input({ name, label, type = "text", required = false, wide = false }: { name: string; label: string; type?: string; required?: boolean; wide?: boolean }) { return <label className={`text-xs font-bold text-slate-600 ${wide ? "sm:col-span-2" : ""}`}>{label}<input name={name} type={type} required={required} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /></label>; }
function Modal({ title, close, submit, children }: { title: string; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => Promise<void>; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => void submit(event)} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ReceiptText className="text-teal-600" size={19} /><h2 className="text-xl font-bold">{title}</h2></div><button type="button" onClick={close}><X size={18} /></button></div><div className="mt-5">{children}</div><button className="mt-6 w-full rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white">Save</button></form></div>; }
