"use client";

import FormSelect from "@/components/form-select";
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";
type Specimen = { id: string; patient_name: string; test_name: string; accession_number: string; specimen_type: string; status: string; rejection_reason: string | null };
export default function Page() { const [items, setItems] = useState<Specimen[]>([]); const [error, setError] = useState(""); async function load() { try { setItems(await api.get<Specimen[]>("/api/v1/hospital/lab/specimens")); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load specimens."); } } useEffect(() => { void load(); }, []); async function update(item: Specimen, status: string) { try { await api.post(`/api/v1/hospital/lab/specimens/${item.id}/status`, { status, rejection_reason: status === "rejected" || status === "retake_required" ? window.prompt("Reason") : null }); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to update specimen."); } }
  return <DashboardShell title="Laboratory specimens" subtitle="Accession, collection, rejection, and retake tracking"><PermissionGate permission="hospital.lab.read" module="laboratory"><main className="mx-auto max-w-[1100px] space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Laboratory operations</p><h1 className="mt-2 text-3xl font-bold">Specimen collection</h1></div><button onClick={() => void load()} className="rounded-xl border border-slate-200 bg-white p-3"><RefreshCw size={17} /></button></header>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{!items.length ? <p className="p-10 text-center text-sm text-slate-500">No specimens accessioned yet. Create specimens from pending laboratory orders.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <article key={item.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><p className="font-bold">{item.patient_name} · {item.test_name}</p><p className="mt-1 text-xs font-mono text-slate-500">{item.accession_number} · {item.specimen_type}</p>{item.rejection_reason && <p className="mt-1 text-xs text-rose-600">{item.rejection_reason}</p>}</div><span className="text-xs font-bold uppercase text-slate-500">{item.status.replaceAll("_", " ")}</span><FormSelect value={item.status} onChange={(event) => void update(item, event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><option value="pending_collection">Pending collection</option><option value="collected">Collected</option><option value="rejected">Rejected</option><option value="retake_required">Retake required</option></FormSelect></article>)}</div>}</section></main></PermissionGate></DashboardShell>; }
