"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { API_BASE } from "@/lib/config";
import { saveTokens, signedInHomePath } from "@/auth";

function deviceId() { const key = "superstore.browser_device_id"; const known = window.localStorage.getItem(key); if (known) return known; const value = crypto.randomUUID(); window.localStorage.setItem(key, value); return value; }
export default function SignupPage() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const tenant_slug = String(form.get("tenant_slug")); const planId = new URLSearchParams(window.location.search).get("plan"); try { const response = await fetch(`${API_BASE}/api/v1/auth/signup`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "include", body: JSON.stringify({ tenant_name: String(form.get("tenant_name")), tenant_slug, full_name: String(form.get("full_name")), email: String(form.get("email")), password: String(form.get("password")), device_id: deviceId() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Unable to create workspace."); saveTokens(data); router.replace(planId ? `/subscribe?plan=${encodeURIComponent(planId)}` : signedInHomePath()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to create workspace."); } finally { setLoading(false); } }
  const planId = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("plan") || "";
  return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-600">New workspace</p><h1 className="mt-2 text-3xl font-bold">Create your account</h1>{planId && <p className="mt-3 rounded-xl bg-teal-50 p-3 text-sm text-teal-800">Your selected annual plan will be ready for secure payment after account creation.</p>}{error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600 sm:col-span-2">Workspace name<input name="tenant_name" required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Workspace URL key<input name="tenant_slug" required pattern="[a-z0-9-]{2,80}" placeholder="your-workspace" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Full name<input name="full_name" required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Email address<input name="email" type="email" required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Password<input name="password" type="password" minLength={8} required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label></div><button disabled={loading} className="mt-5 w-full rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{loading ? "Creating workspace…" : "Create workspace"}</button><Link href={planId ? `/login?next=${encodeURIComponent(`/subscribe?plan=${planId}`)}` : "/login"} className="mt-5 block text-center text-sm font-bold text-teal-700">Already have an account? Sign in</Link></form></main>;
}
