"use client";

import FormSelect from "@/components/form-select";
import { FormEvent, useEffect, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";
type Patient = { id: string; full_name: string; patient_number: string }; type Plan = { id: string; goals: string; instructions: string; follow_up_date: string | null; status: string };
export default function Page() { const [patients, setPatients] = useState<Patient[]>([]); const [patientId, setPatientId] = useState(""); const [items, setItems] = useState<Plan[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(""); async function loadPatients() { try { const p = await api.get<Patient[]>("/api/v1/clinical/patients"); setPatients(p); setPatientId((v) => v || p[0]?.id || ""); } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to load patients."); } } async function load() { if (!patientId) return; try { setItems(await api.get<Plan[]>(`/api/v1/hospital/clinical/treatment-plans/${patientId}`)); } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to load treatment plans."); } } useEffect(() => { void loadPatients(); }, []); useEffect(() => { void load(); }, [patientId]); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); try { await api.post("/api/v1/hospital/clinical/treatment-plans", { patient_id: patientId, goals: d.get("goals"), instructions: d.get("instructions"), follow_up_date: d.get("follow_up_date") || null }); setOpen(false); await load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to save plan."); } }
  return <DashboardShell title="Treatment plans" subtitle="Goals, care instructions, and follow-up planning"><PermissionGate permission="hospital.patients.read" module="hospital"><main className="mx-auto max-w-[1000px] space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Clinical consultation</p><h1 className="mt-2 text-3xl font-bold">Treatment plans</h1></div><div className="flex gap-2"><button onClick={() => void load()} className="rounded-xl border border-slate-200 bg-white p-3"><RefreshCw size={17} /></button><button onClick={() => setOpen(true)} disabled={!patientId} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white"><Plus size={16} /> Add plan</button></div></header>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<FormSelect value={patientId} onChange={(e) => setPatientId(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option value="">Select patient</option>{patients.map((p) => <option key={p.id} value={p.id}>{p.full_name} ({p.patient_number})</option>)}</FormSelect><section className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><p className="font-bold">{item.goals}</p><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-bold text-teal-700">{item.status}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{item.instructions}</p>{item.follow_up_date && <p className="mt-2 text-xs text-slate-400">Follow-up: {item.follow_up_date}</p>}</article>)}{!items.length && <p className="text-sm text-slate-500">No treatment plans recorded.</p>}</section>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(e) => void submit(e)} className="w-full max-w-md rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">Add treatment plan</h2><textarea name="goals" required rows={3} placeholder="Treatment goals" className="mt-5 w-full rounded-xl border border-slate-200 p-3 text-sm" /><textarea name="instructions" required rows={5} placeholder="Instructions and care plan" className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm" /><input name="follow_up_date" type="date" className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm" /><div className="mt-5 flex gap-2"><button type="button" onClick={() => setOpen(false)} className="flex-1 rounded-xl border border-slate-200 py-3 text-sm font-bold">Cancel</button><button className="flex-1 rounded-xl bg-teal-600 py-3 text-sm font-bold text-white">Save</button></div></form></div>}</main></PermissionGate></DashboardShell>; }
