"use client";

import FormSelect from "@/components/form-select";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { KeyRound, Laptop, LockKeyhole, Search, ShieldCheck, UserCog, UserPlus, Users, X } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { useToast } from "@/components/toast-provider";
import { api, ApiError } from "@/lib/api";

type Branch = { id: string; name: string; code: string; active?: boolean };
type Role = { id: string; name: string; description: string; is_system: boolean; is_global: boolean };
type Permission = { code: string; description: string; module?: string };
type RolePermission = { permission_code: string; effect: "allow" | "deny"; conditions: Record<string, unknown> };
type Override = RolePermission & { description: string; expires_at: string | null };
type Access = { has_login: boolean; enabled: boolean; role: string | null; role_id: string | null; branch_ids: string[]; password_must_change: boolean; last_login_at: string | null; open_cash_session: { number: string; cash_point_number: number | null } | null };
type Staff = { id: string; user_id: string | null; employee_number: string; name: string; email: string; phone: string | null; role: string; job_title: string | null; department: string | null; branch_id: string | null; branch_name: string | null; supervisor_id: string | null; hire_date: string | null; employment_status: string; access: Access };
type Modal = "new" | "profile" | "access" | "roles" | "newRole" | "rolePermissions" | "userPermissions" | "reset" | "revoke" | null;
type Choice = "allow" | "deny" | "none";
type Choices = Record<string, { effect: Choice; conditions: Record<string, unknown> }>;

const label = (value: string | null) => value === "store_cashier" ? "Salesperson / cashier" : value === "no_access" ? "No access role" : (value || "").replaceAll("_", " ").replace(/\b\w/g, (part) => part.toUpperCase());
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never";

export default function PeoplePage() {
  const toast = useToast();
  const [staff, setStaff] = useState<Staff[]>([]); const [roles, setRoles] = useState<Role[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]);
  const [selected, setSelected] = useState<Staff | null>(null); const [selectedRole, setSelectedRole] = useState<Role | null>(null); const [overrides, setOverrides] = useState<Override[]>([]); const [choices, setChoices] = useState<Choices>({}); const [newRolePermissions, setNewRolePermissions] = useState<string[]>([]);
  const [modal, setModal] = useState<Modal>(null); const [query, setQuery] = useState(""); const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false);
  const showError = useCallback((error: unknown, fallback: string) => toast.error(fallback, error instanceof ApiError ? error.message : "Please try again."), [toast]);
  const load = useCallback(async (showFailure = true) => {
    setBusy(true); const result = await Promise.allSettled([api.get<Staff[]>("/api/v1/employees/directory"), api.get<Role[]>("/api/v1/employees/access-roles"), api.get<Branch[]>("/api/v1/catalog/branches"), api.get<Permission[]>("/api/v1/employees/access-permissions")]);
    if (result[0].status === "fulfilled") setStaff(result[0].value); if (result[1].status === "fulfilled") setRoles(result[1].value); if (result[2].status === "fulfilled") setBranches(result[2].value); if (result[3].status === "fulfilled") setPermissions(result[3].value);
    if (showFailure && result[0].status === "rejected") showError(result[0].reason, "Unable to load staff"); setBusy(false);
  }, [showError]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const visible = useMemo(() => staff.filter((person) => `${person.name} ${person.email} ${person.employee_number} ${person.job_title || ""} ${person.access.role || ""}`.toLowerCase().includes(query.toLowerCase())), [staff, query]);
  const close = () => { setModal(null); setSelectedRole(null); setChoices({}); setNewRolePermissions([]); setOverrides([]); };
  const refresh = async (message?: string) => { await load(false); if (message) toast.success(message); };

  async function createStaff(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const login = form.get("create_login") === "on"; setSaving(true); try { await api.post("/api/v1/employees", { name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone") || "") || null, job_title: String(form.get("job_title") || "") || null, department: String(form.get("department") || "") || null, role: String(form.get("work_role") || "staff"), branch_id: String(form.get("branch_id") || "") || null, hire_date: String(form.get("hire_date") || "") || null, employment_status: "active", create_login: login, temporary_password: login ? String(form.get("temporary_password")) : null, access_role_id: login ? String(form.get("access_role_id")) : null }); close(); await refresh("Staff member saved."); } catch (error) { showError(error, "Unable to create staff member"); } finally { setSaving(false); } }
  async function updateProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); setSaving(true); try { await api.put(`/api/v1/employees/${selected.id}`, { name: String(form.get("name")), email: selected.user_id ? selected.email : String(form.get("email")), phone: String(form.get("phone") || "") || null, job_title: String(form.get("job_title") || "") || null, department: String(form.get("department") || "") || null, role: selected.role, branch_id: String(form.get("branch_id") || "") || null, hire_date: String(form.get("hire_date") || "") || null, employment_status: String(form.get("employment_status")) }); if (selected.access.has_login) { const roleId = String(form.get("access_role_id") || ""); if (!roleId && selected.access.role_id) await api.delete(`/api/v1/employees/${selected.id}/access/role`); else if (roleId && roleId !== selected.access.role_id) await api.patch(`/api/v1/employees/${selected.id}/access`, { role_id: roleId, access_enabled: selected.access.enabled }); } close(); await refresh("Profile and user role updated."); } catch (error) { showError(error, "Unable to update profile"); } finally { setSaving(false); } }
  async function updateAccess(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const roleId = String(form.get("access_role_id") || ""); setSaving(true); try { if (selected.access.has_login) { if (!roleId) await api.delete(`/api/v1/employees/${selected.id}/access/role`); else await api.patch(`/api/v1/employees/${selected.id}/access`, { role_id: roleId, access_enabled: form.get("access_enabled") === "on" }); } else await api.post(`/api/v1/employees/${selected.id}/access`, { role_id: roleId, temporary_password: String(form.get("temporary_password")) }); close(); await refresh(roleId ? "User role and access updated." : "User role removed. Direct permissions, if any, remain."); } catch (error) { showError(error, "Unable to update user access"); } finally { setSaving(false); } }
  async function resetPassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); setSaving(true); try { await api.post(`/api/v1/employees/${selected.id}/access/reset-password`, { temporary_password: String(form.get("temporary_password")) }); close(); await refresh("Temporary password set and sessions revoked."); } catch (error) { showError(error, "Unable to reset password"); } finally { setSaving(false); } }
  async function revokeSessions() { if (!selected) return; setSaving(true); try { const result = await api.post<{ revoked_sessions: number }>(`/api/v1/employees/${selected.id}/access/revoke-sessions`, {}); close(); await refresh(`${result.revoked_sessions} sessions revoked.`); } catch (error) { showError(error, "Unable to revoke sessions"); } finally { setSaving(false); } }

  async function openRolePermissions(role: Role) { setSaving(true); try { const result = await api.get<{ permissions: RolePermission[] }>(`/api/v1/auth/roles/${role.id}/permissions`); setSelectedRole(role); setChoices(Object.fromEntries(result.permissions.map((item) => [item.permission_code, { effect: item.effect, conditions: item.conditions || {} }]))); setModal("rolePermissions"); } catch (error) { showError(error, "Unable to load role permissions"); } finally { setSaving(false); } }
  async function saveRolePermissions(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedRole) return; setSaving(true); try { await api.put(`/api/v1/auth/roles/${selectedRole.id}/permissions`, Object.entries(choices).filter(([, item]) => item.effect !== "none").map(([permission_code, item]) => ({ permission_code, effect: item.effect, conditions: item.conditions }))); close(); await refresh("Role permissions updated."); } catch (error) { showError(error, "Unable to update role permissions"); } finally { setSaving(false); } }
  async function createRole(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { await api.post("/api/v1/auth/roles", { name: String(form.get("name")), description: String(form.get("description") || ""), permission_codes: newRolePermissions, conditions: {}, is_global: false }); close(); await refresh("Custom role created."); } catch (error) { showError(error, "Unable to create role"); } finally { setSaving(false); } }
  async function openOverrides(person: Staff) { if (!person.access.has_login) return; setSaving(true); try { setOverrides(await api.get<Override[]>(`/api/v1/employees/${person.id}/permission-overrides`)); setSelected(person); setModal("userPermissions"); } catch (error) { showError(error, "Unable to load direct permissions"); } finally { setSaving(false); } }
  async function saveOverride(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); setSaving(true); try { const expiry = String(form.get("expires_at") || ""); const record = await api.put<Override>(`/api/v1/employees/${selected.id}/permission-overrides`, { permission_code: String(form.get("permission_code")), effect: String(form.get("effect")), expires_at: expiry ? new Date(expiry).toISOString() : null, conditions: {} }); setOverrides((current) => [...current.filter((item) => item.permission_code !== record.permission_code), record].sort((a, b) => a.permission_code.localeCompare(b.permission_code))); await load(false); toast.success("Direct permission saved."); event.currentTarget.reset(); } catch (error) { showError(error, "Unable to save direct permission"); } finally { setSaving(false); } }
  async function revokeOverride(code: string) { if (!selected) return; setSaving(true); try { await api.delete(`/api/v1/employees/${selected.id}/permission-overrides/${encodeURIComponent(code)}`); setOverrides((current) => current.filter((item) => item.permission_code !== code)); await load(false); toast.success("Direct permission revoked."); } catch (error) { showError(error, "Unable to revoke direct permission"); } finally { setSaving(false); } }

  return <DashboardShell title="People & access" subtitle="Staff profiles, user roles, permissions, branch scope, and account security"><PermissionGate permission="users.read" allowedRoles={["owner", "admin", "platform_admin", "platform_super_admin"]}><div className="mx-auto max-w-[1320px] space-y-6">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Staff administration</p><h1 className="mt-2 text-3xl font-bold tracking-tight">People & access</h1><p className="mt-2 text-sm text-slate-500">Roles are the normal access policy. Direct permissions are recorded, revocable exceptions.</p></div><div className="flex gap-2"><button onClick={() => setModal("roles")} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700"><ShieldCheck className="mr-2 inline" size={16} />Roles & permissions</button><button onClick={() => setModal("new")} className="rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white"><UserPlus className="mr-2 inline" size={16} />Add staff</button></div></header>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Employees" value={staff.length} icon={<Users size={18} />} /><Metric label="System logins" value={staff.filter((person) => person.access.has_login).length} icon={<LockKeyhole size={18} />} /><Metric label="Pending password changes" value={staff.filter((person) => person.access.password_must_change).length} icon={<KeyRound size={18} />} /></div>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-3 text-slate-400" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, staff number, or user role…" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm" /></label></section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-xl font-bold">Staff directory</h2><p className="mt-1 text-xs text-slate-500">{visible.length} of {staff.length} employees</p></div>{busy && <span className="text-xs text-slate-400">Refreshing…</span>}</div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-6 py-3">Employee</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">User role</th><th className="px-4 py-3">Security & POS</th><th className="px-6 py-3 text-right">Manage</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((person) => <tr key={person.id}><td className="px-6 py-4"><p className="font-bold">{person.name}</p><p className="text-xs text-teal-700">{person.employee_number}{person.job_title ? ` · ${person.job_title}` : ""}</p><p className="mt-1 text-xs text-slate-400">{person.email}</p></td><td className="px-4 py-4"><p>{person.branch_name || "No primary branch"}</p><p className="mt-1 text-xs text-slate-400">{person.department || "No department"}</p></td><td className="px-4 py-4"><Pill tone={person.access.enabled ? "green" : "slate"}>{person.access.has_login ? label(person.access.role) : "No login"}</Pill><p className="mt-2 text-xs text-slate-500">{person.access.has_login ? `${person.access.branch_ids.length || "All"} branch scope` : "Employment record only"}</p></td><td className="px-4 py-4"><p className="flex items-center gap-1.5 text-xs"><Laptop size={13} />{person.access.last_login_at ? dateTime(person.access.last_login_at) : "No sign-in yet"}</p>{person.access.open_cash_session ? <p className="mt-2 text-xs font-bold text-amber-700">{person.access.open_cash_session.number}{person.access.open_cash_session.cash_point_number ? ` · POS ${person.access.open_cash_session.cash_point_number}` : ""} open</p> : <p className="mt-2 text-xs text-slate-400">No open cash session</p>}</td><td className="px-6 py-4 text-right"><button onClick={() => { setSelected(person); setModal("profile"); }} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Manage</button></td></tr>)}</tbody></table></div></section>
    {modal === "new" && <Dialog title="Add staff member" close={close}><form onSubmit={createStaff} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input name="name" label="Full name" required /><Input name="email" label="Work email" type="email" required /><Input name="phone" label="Phone number" /><Input name="job_title" label="Job title" /><Input name="department" label="Department" /><Input name="hire_date" label="Hire date" type="date" /><Select name="work_role" label="Work category"><option value="staff">Staff</option><option value="salesperson">Salesperson</option><option value="cashier">Cashier</option><option value="manager">Manager</option></Select><Select name="branch_id" label="Primary branch"><option value="">No primary branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></div><LoginFields roles={roles} branches={branches} /><Save busy={saving}>Create staff member</Save></form></Dialog>}
    {modal === "profile" && selected && <Dialog title={`Profile · ${selected.name}`} close={close}><form onSubmit={updateProfile} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input name="name" label="Full name" defaultValue={selected.name} required /><Input name="email" label="Work email" type="email" defaultValue={selected.email} disabled={Boolean(selected.user_id)} /><Input name="phone" label="Phone number" defaultValue={selected.phone || ""} /><Input name="job_title" label="Job title" defaultValue={selected.job_title || ""} /><Input name="department" label="Department" defaultValue={selected.department || ""} /><Input name="hire_date" label="Hire date" type="date" defaultValue={selected.hire_date || ""} />{selected.access.has_login ? <Select name="access_role_id" label="User role (controls permissions)" defaultValue={selected.access.role_id || ""}><option value="">No access role</option>{roles.map((role) => <option key={role.id} value={role.id}>{label(role.name)}</option>)}</Select> : <p className="rounded-xl border border-dashed border-slate-200 p-3 text-xs text-slate-500">Grant a login before selecting a user role.</p>}<Select name="employment_status" label="Employment status" defaultValue={selected.employment_status}><option value="active">Active</option><option value="on_leave">On leave</option><option value="suspended">Suspend</option><option value="terminated">Terminate</option></Select><Select name="branch_id" label="Primary branch" defaultValue={selected.branch_id || ""}><option value="">No primary branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></div><Save busy={saving}>Save profile and user role</Save></form><Actions selected={selected} setModal={setModal} openOverrides={openOverrides} /></Dialog>}
    {modal === "access" && selected && <Dialog title={`Role & access scope · ${selected.name}`} close={close}><form onSubmit={updateAccess} className="space-y-4"><p className="rounded-2xl bg-slate-50 p-3 text-xs text-slate-600">This is the real system role. Selecting “No access role” removes the role; direct permissions remain as controlled exceptions.</p><Select name="access_role_id" label="User role (controls permissions)" defaultValue={selected.access.role_id || ""} required={!selected.access.has_login}><option value="">No access role</option>{roles.map((role) => <option key={role.id} value={role.id}>{label(role.name)} · {role.description}</option>)}</Select>{!selected.access.has_login && <Input name="temporary_password" label="Temporary password" type="password" required minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9])\S{12,}" title="At least 12 characters with uppercase, lowercase, a number, and a symbol. No spaces." hint="12+ characters with uppercase, lowercase, a number, and a symbol." />}<BranchScope branches={branches} selectedIds={selected.access.branch_ids} />{selected.access.has_login && <label className="flex gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input name="access_enabled" type="checkbox" defaultChecked={selected.access.enabled} /><span><strong>System access enabled</strong><span className="block text-xs text-slate-500">Close any open cash session before disabling access or removing a role.</span></span></label>}<Save busy={saving}>Save role & access</Save></form></Dialog>}
    {modal === "userPermissions" && selected && <Dialog title={`Direct permissions · ${selected.name}`} close={close}><div className="space-y-4"><p className="rounded-2xl bg-teal-50 p-3 text-xs leading-5 text-teal-900">Allow grants only this user access. Deny removes access even when the role allows it. Set an expiry for temporary permission.</p><form onSubmit={saveOverride} className="grid gap-3 rounded-2xl border border-slate-200 p-4 sm:grid-cols-2"><Select name="permission_code" label="Permission" required><option value="">Select permission</option>{permissions.map((permission) => <option key={permission.code} value={permission.code}>{permission.code} · {permission.description}</option>)}</Select><Select name="effect" label="Override"><option value="allow">Allow this user</option><option value="deny">Deny this user</option></Select><Input name="expires_at" label="Expiry (optional)" type="datetime-local" /><button disabled={saving} className="rounded-xl bg-teal-600 px-3 py-2 text-sm font-bold text-white">Save direct permission</button></form><div className="space-y-2">{overrides.map((item) => <div key={item.permission_code} className="flex gap-3 rounded-xl border border-slate-200 p-3"><div className="min-w-0 flex-1"><p className="font-bold text-sm">{item.permission_code}</p><p className="text-xs text-slate-500">{item.description} · {item.effect === "allow" ? "Allowed" : "Denied"}{item.expires_at ? ` until ${dateTime(item.expires_at)}` : ""}</p></div><button type="button" disabled={saving} onClick={() => void revokeOverride(item.permission_code)} className="text-xs font-bold text-rose-700">Revoke</button></div>)}{!overrides.length && <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">No direct permissions. This user relies on their role.</p>}</div></div></Dialog>}
    {modal === "roles" && <Dialog title="Roles & permissions" close={close}><div className="space-y-4"><p className="text-sm text-slate-600">Custom roles can receive, deny, and revoke permissions. Built-in roles are protected so their baseline stays reliable; create a custom role for a company-specific variation.</p><button onClick={() => setModal("newRole")} className="rounded-xl bg-teal-600 px-4 py-2 text-sm font-bold text-white">Create custom role</button>{roles.map((role) => <div key={role.id} className="flex gap-3 rounded-xl border border-slate-200 p-3"><div className="min-w-0 flex-1"><p className="font-bold">{label(role.name)}</p><p className="text-xs text-slate-500">{role.description || (role.is_system ? "Built-in role" : "Custom role")}</p></div><button onClick={() => void openRolePermissions(role)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">{role.is_system ? "View permissions" : "Manage permissions"}</button></div>)}</div></Dialog>}
    {modal === "newRole" && <Dialog title="Create custom role" close={close}><form onSubmit={createRole} className="space-y-4"><Input name="name" label="Role name" required /><label className="block text-xs font-bold">Description<textarea name="description" rows={2} className="mt-1 w-full rounded-xl border border-slate-200 p-2 text-sm" /></label><PermissionChecks permissions={permissions} selected={newRolePermissions} toggle={(code) => setNewRolePermissions((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code])} /><Save busy={saving}>Create role</Save></form></Dialog>}
    {modal === "rolePermissions" && selectedRole && <Dialog title={`Permissions · ${label(selectedRole.name)}`} close={close}>{selectedRole.is_system ? <div className="space-y-3"><p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">This built-in role is protected. Create a custom role, edit its permissions, and assign it to the user for a company-specific policy.</p><PermissionView permissions={permissions} choices={choices} /></div> : <form onSubmit={saveRolePermissions} className="space-y-4"><p className="text-sm text-slate-600">Allow applies to every user with this role. Deny removes it. Not assigned revokes it from this role.</p><PermissionChoices permissions={permissions} choices={choices} setChoice={(code, effect) => setChoices((current) => ({ ...current, [code]: { effect, conditions: current[code]?.conditions || {} } }))} /><Save busy={saving}>Save role permissions</Save></form>}</Dialog>}
    {modal === "reset" && selected && <Dialog title={`Reset password · ${selected.name}`} close={close}><form onSubmit={resetPassword} className="space-y-4"><Input name="temporary_password" label="New temporary password" type="password" required minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9])\S{12,}" title="At least 12 characters with uppercase, lowercase, a number, and a symbol. No spaces." hint="12+ characters with uppercase, lowercase, a number, and a symbol." /><Save busy={saving}>Set password and revoke sessions</Save></form></Dialog>}
    {modal === "revoke" && selected && <Dialog title={`Revoke sessions · ${selected.name}`} close={close}><p className="mb-4 text-sm text-slate-600">This signs the employee out of every active session.</p><button disabled={saving} onClick={() => void revokeSessions()} className="w-full rounded-xl bg-rose-600 px-4 py-3 text-sm font-bold text-white">{saving ? "Revoking…" : "Revoke sessions"}</button></Dialog>}
  </div></PermissionGate></DashboardShell>;
}

function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between text-teal-600"><p className="text-xs font-bold uppercase text-slate-400">{label}</p>{icon}</div><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
function Pill({ tone, children }: { tone: "green" | "slate"; children: React.ReactNode }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${tone === "green" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{children}</span>; }
function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div role="dialog" aria-modal="true" aria-label={title} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-xl"><div className="flex justify-between gap-4"><h2 className="text-xl font-bold">{title}</h2><button onClick={close} aria-label="Close dialog" className="text-slate-400"><X size={20} /></button></div><div className="mt-5">{children}</div></div></div>; }
function Input({ name, label, type = "text", required = false, defaultValue, disabled = false, hint, pattern, minLength, title }: { name: string; label: string; type?: string; required?: boolean; defaultValue?: string; disabled?: boolean; hint?: string; pattern?: string; minLength?: number; title?: string }) { return <label className="block text-xs font-bold text-slate-600">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} disabled={disabled} pattern={pattern} minLength={minLength} title={title} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm disabled:bg-slate-100" />{hint && <span className="mt-1 block text-[11px] font-medium leading-4 text-slate-400">{hint}</span>}</label>; }
function Select({ name, label, children, defaultValue, required = false }: { name: string; label: string; children: React.ReactNode; defaultValue?: string; required?: boolean }) { return <label className="block text-xs font-bold text-slate-600">{label}<FormSelect name={name} required={required} defaultValue={defaultValue} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm">{children}</FormSelect></label>; }
function Save({ busy, children }: { busy: boolean; children: React.ReactNode }) { return <button disabled={busy} className="w-full rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? "Saving…" : children}</button>; }
function BranchScope({ branches: _branches, selectedIds: _selectedIds }: { branches: Branch[]; selectedIds: string[] }) { return <p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Branch visibility follows the employee’s primary branch. Choose “No primary branch” on the profile to allow all company branches.</p>; }
function LoginFields({ roles, branches: _branches }: { roles: Role[]; branches: Branch[] }) { const [enabled, setEnabled] = useState(false); return <div className="rounded-2xl border border-teal-100 bg-teal-50/50 p-4"><label className="flex gap-3 text-sm"><input name="create_login" type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /><span><strong>Give this employee a system login</strong><span className="block text-xs text-slate-500">They change their temporary password on first sign-in.</span></span></label>{enabled && <div className="mt-4 grid gap-4 sm:grid-cols-2"><Input name="temporary_password" label="Temporary password" type="password" required minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9])\S{12,}" title="At least 12 characters with uppercase, lowercase, a number, and a symbol. No spaces." hint="12+ characters with uppercase, lowercase, a number, and a symbol." /><Select name="access_role_id" label="User role (controls permissions)" required><option value="">Select role</option>{roles.map((role) => <option key={role.id} value={role.id}>{label(role.name)}</option>)}</Select><p className="sm:col-span-2 rounded-xl bg-white p-3 text-xs text-slate-500">Branch visibility follows the primary branch selected above. Leave it as “No primary branch” to allow all company branches.</p></div>}</div>; }
function Actions({ selected, setModal, openOverrides }: { selected: Staff; setModal: (value: Modal) => void; openOverrides: (person: Staff) => Promise<void> }) { return <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold uppercase text-slate-400">Account actions</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => setModal("access")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><UserCog className="mr-1 inline" size={14} />{selected.access.has_login ? "Role & access scope" : "Grant login & set role"}</button>{selected.access.has_login && <><button onClick={() => void openOverrides(selected)} className="rounded-xl border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800"><ShieldCheck className="mr-1 inline" size={14} />Direct permissions</button><button onClick={() => setModal("reset")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><KeyRound className="mr-1 inline" size={14} />Reset password</button><button onClick={() => setModal("revoke")} className="rounded-xl border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700"><Laptop className="mr-1 inline" size={14} />Revoke sessions</button></>}</div></div>; }
function PermissionChecks({ permissions, selected, toggle }: { permissions: Permission[]; selected: string[]; toggle: (code: string) => void }) { return <div className="max-h-64 space-y-2 overflow-y-auto rounded-2xl bg-slate-50 p-3">{permissions.map((permission) => <label key={permission.code} className="flex gap-2 text-xs"><input type="checkbox" checked={selected.includes(permission.code)} onChange={() => toggle(permission.code)} /><span><strong>{permission.code}</strong><span className="ml-1 text-slate-400">{permission.description}</span></span></label>)}</div>; }
function PermissionChoices({ permissions, choices, setChoice }: { permissions: Permission[]; choices: Choices; setChoice: (code: string, choice: Choice) => void }) { return <div className="max-h-[55vh] space-y-2 overflow-y-auto rounded-2xl bg-slate-50 p-3">{permissions.map((permission) => <div key={permission.code} className="flex gap-3 rounded-xl bg-white p-3"><div className="min-w-0 flex-1"><p className="text-xs font-bold">{permission.code}</p><p className="text-[11px] text-slate-500">{permission.description}{Object.keys(choices[permission.code]?.conditions || {}).length ? " · Conditional" : ""}</p></div><FormSelect value={choices[permission.code]?.effect || "none"} onChange={(event) => setChoice(permission.code, event.target.value as Choice)} className="rounded-lg border border-slate-200 px-2 text-xs"><option value="none">Not assigned</option><option value="allow">Allow</option><option value="deny">Deny</option></FormSelect></div>)}</div>; }
function PermissionView({ permissions, choices }: { permissions: Permission[]; choices: Choices }) { const assigned = permissions.filter((permission) => choices[permission.code]?.effect && choices[permission.code].effect !== "none"); return <div className="space-y-2">{assigned.map((permission) => <div key={permission.code} className="rounded-xl border border-slate-200 p-3"><p className="text-xs font-bold">{permission.code} · {choices[permission.code].effect}</p><p className="text-[11px] text-slate-500">{permission.description}</p></div>)}{!assigned.length && <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">No permission assignments.</p>}</div>; }
