"use client";

import { FormEvent, useEffect, useState } from "react";
import { LogOut, RefreshCw } from "lucide-react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";

type Admission = { id: string; patient_name: string; bed_number: string; status: string; reason: string | null; admitted_at: string };

export default function Page() {
  const [items, setItems] = useState<Admission[]>([]); const [selected, setSelected] = useState<Admission | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setBusy(true); try { setItems(await api.get<Admission[]>("/api/v1/hospital/admissions")); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load admissions."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const notes = String(new FormData(event.currentTarget).get("notes") || "").trim(); if (!notes) { setError("Enter discharge instructions or a summary before discharging."); return; } try { await api.post(`/api/v1/hospital/admissions/${selected.id}/discharge`, { notes }); setSelected(null); setNotice("Patient discharged and bed released."); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to discharge patient."); } }
  const active = items.filter((item) => item.status === "admitted");
  return <DashboardShell title="Discharge summaries" subtitle="Complete inpatient care with documented instructions"><PermissionGate permission="hospital.admissions.manage" module="hospital"><main className="mx-auto max-w-[1100px] space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-600">Inpatient care</p><h1 className="mt-2 text-3xl font-bold">Discharge summaries</h1></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold"><RefreshCw size={16} /> Refresh</button></header>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</p>}<section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{busy ? <p className="p-8 text-sm text-slate-500">Loading admissions…</p> : !active.length ? <p className="p-10 text-center text-sm text-slate-500">No admitted patients require discharge.</p> : <div className="divide-y divide-slate-100">{active.map((item) => <article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-bold">{item.patient_name}</p><p className="mt-1 text-sm text-slate-500">Bed {item.bed_number} · {item.reason || "No admission reason recorded"}</p></div><button onClick={() => setSelected(item)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 py-2.5 text-xs font-bold text-white"><LogOut size={15} /> Discharge</button></article>)}</div>}</section>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => void submit(event)} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">Discharge {selected.patient_name}</h2><p className="mt-1 text-sm text-slate-500">Bed {selected.bed_number} will be released after saving.</p><label className="mt-5 block text-xs font-bold text-slate-600">Discharge summary and follow-up instructions<textarea name="notes" required rows={6} className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Outcome, medications, warning signs, and follow-up plan" /></label><div className="mt-5 flex gap-2"><button type="button" onClick={() => setSelected(null)} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</button><button className="flex-1 rounded-xl bg-rose-600 px-4 py-3 text-sm font-bold text-white">Complete discharge</button></div></form></div>}</main></PermissionGate></DashboardShell>;
}
