"use client";
import { FormEvent, useEffect, useState } from "react";
import DashboardShell from "@/components/dashboard-shell";
import PermissionGate from "@/components/permission-gate";
import { api, ApiError } from "@/lib/api";
type Patient = { id: string; full_name: string; patient_number: string };

export default function Page() {
  const [patients, setPatients] = useState<Patient[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void api.get<Patient[]>("/api/v1/clinical/patients").then(setPatients).catch((caught) => setError(caught instanceof ApiError ? caught.message : "Unable to load patients.")); }, []);
  async function submit(event: FormEvent<HTMLFormElement>, action: "credit" | "refund") { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(""); try { const path = action === "credit" ? "credit" : "refund"; const field = action === "credit" ? { amount: form.get("amount"), description: form.get("description") } : { amount: form.get("amount"), reason: form.get("reason") }; const result = await api.post<{ balance: string; currency: string }>(`/api/v1/hospital/patients/${form.get("patient_id")}/wallet/${path}`, field); setNotice(`Wallet ${action === "credit" ? "credited" : "refunded"}. New balance: ${Number(result.balance).toLocaleString(undefined, { style: "currency", currency: result.currency })}.`); event.currentTarget.reset(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : `Unable to ${action} wallet.`); } finally { setSaving(false); } }
  const patientsField = <select name="patient_id" required className="mt-1 w-full rounded-xl border border-slate-200 p-3"><option value="">Select patient</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.full_name} ({patient.patient_number})</option>)}</select>;
  return <DashboardShell title="Patient wallets" subtitle="Record wallet credits and controlled refunds"><PermissionGate permission="hospital.billing.post" module="hospital"><main className="mx-auto max-w-[900px] space-y-6"><header><h1 className="text-3xl font-bold">Patient wallet operations</h1><p className="mt-2 text-sm text-slate-500">Credits and refunds are authorized billing actions with ledger, accounting, and audit records.</p></header>{notice && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<form onSubmit={(event) => void submit(event, "credit")} className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Credit wallet</h2><label className="block text-sm font-bold">Patient{patientsField}</label><label className="block text-sm font-bold">Amount received<input name="amount" type="number" min="0.01" step="0.01" required className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label><label className="block text-sm font-bold">Description<input name="description" required minLength={2} maxLength={240} placeholder="Cash receipt or transfer reference" className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label><button disabled={saving} className="w-full rounded-xl bg-teal-600 p-3 text-sm font-bold text-white disabled:opacity-60">Credit patient wallet</button></form><form onSubmit={(event) => void submit(event, "refund")} className="space-y-5 rounded-3xl border border-rose-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Refund wallet</h2><label className="block text-sm font-bold">Patient{patientsField}</label><label className="block text-sm font-bold">Refund amount<input name="amount" type="number" min="0.01" step="0.01" required className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label><label className="block text-sm font-bold">Refund reason<input name="reason" required minLength={2} maxLength={240} placeholder="Reason for refund" className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label><button disabled={saving} className="w-full rounded-xl bg-rose-600 p-3 text-sm font-bold text-white disabled:opacity-60">Process refund</button></form></main></PermissionGate></DashboardShell>;
}
